export const RouteMapModel: Record<string, string> = {
    'Home' : '/',
    'B.tech MnC' : '/academics/btech',
    'General UG' : '/academics/generalUG',
    'M.Sc' : '/academics/msc',
    'Ph.D' : '/academics/phd',
    'Minors in Maths' : '/academics/minors',
    'Curriculum' : '/academics/curriculum',
    'Areas' : '/research/areas',
    'Publications' : '/research/publications',
    'Funded Projects' : '/research/fundedprojects',
    'Faculty' : '/people/faculty',
    'Staff' : '/people/staff',
    'Alumni' : '/people/alumni',
    'Post-doctoral Fellows' : '/people/postdoctoral',
    'Doctoral Students' : '/people/doctoral',
    'B.Tech & M.Sc' : '/people/btech_msc', 
    'Awardees' : '/people/awardees',
    'Seminars' : '/news/seminars',
    'Events' : '/news/events',
    'Outreach Events' : '/news/outreach',
    'Ph.D Admissions' : '/admissions/phd',
    'Summer Internships' : '/admissions/summerintern',
    'Faculty Recruitments' : '/recruitments/faculty',
    'Project Openings' : '/recruitments/project_openings',
}